"""ATLAS veri modelleri."""

from app.models.agent_log import AgentLogCreate, AgentLogRecord, AgentLogResponse
from app.models.communication import (
    BulkSendResult,
    CommunicationAnalysisResult,
    CommunicationConfig,
    EmailLanguage,
    EmailMessage,
    EmailRecipient,
    EmailTaskType,
    EmailTemplate,
    EmailTone,
    FollowUpEntry,
    FollowUpStatus,
    InboxMessage,
    ResponseAnalysis,
    ResponseSentiment,
)
from app.models.coding import (
    CodeAnalysisResult,
    CodeIssue,
    CodeLanguage,
    CodeQualityMetrics,
    CodeTaskType,
    CodingConfig,
    SecurityVulnerability,
    SeverityLevel,
    VulnerabilityType,
)
from app.models.decision import DecisionCreate, DecisionRecord, DecisionResponse
from app.models.marketing import (
    AdCheckType,
    AdDisapproval,
    BudgetRecommendation,
    CampaignMetrics,
    KeywordMetrics,
    MarketingAnalysisResult,
    MarketingConfig,
    PerformanceLevel,
)
from app.models.research import (
    CompanyInfo,
    ReliabilityLevel,
    ResearchConfig,
    ResearchResult,
    ResearchType,
    ScrapedPage,
    SupplierScore,
    WebSearchResult,
)
from app.models.security import (
    BannedIPEntry,
    FailedLoginEntry,
    OpenPort,
    SecurityCheckType,
    SecurityScanConfig,
    SecurityScanResult,
    SSLCertInfo,
    SuspiciousProcess,
    ThreatLevel,
)
from app.models.server import (
    CpuMetrics,
    DiskMetrics,
    MetricStatus,
    MetricThresholds,
    RamMetrics,
    ServerConfig,
    ServerMetrics,
    ServiceStatus,
)
from app.models.notification import (
    NotificationChannel,
    NotificationCreate,
    NotificationEventType,
    NotificationPriority,
    NotificationRecord,
    NotificationResponse,
    NotificationStatus,
)
from app.models.task import TaskCreate, TaskRecord, TaskResponse, TaskStatus
from app.models.voice import (
    CommandAnalysis,
    CommandIntent,
    SynthesisResult,
    TranscriptionResult,
    VoiceAnalysisResult,
    VoiceConfig,
    VoiceLanguage,
    VoiceTaskType,
)

__all__ = [
    # Iletisim modelleri
    "BulkSendResult",
    "CommunicationAnalysisResult",
    "CommunicationConfig",
    "EmailLanguage",
    "EmailMessage",
    "EmailRecipient",
    "EmailTaskType",
    "EmailTemplate",
    "EmailTone",
    "FollowUpEntry",
    "FollowUpStatus",
    "InboxMessage",
    "ResponseAnalysis",
    "ResponseSentiment",
    # Coding modelleri
    "CodeAnalysisResult",
    "CodeIssue",
    "CodeLanguage",
    "CodeQualityMetrics",
    "CodeTaskType",
    "CodingConfig",
    "SecurityVulnerability",
    "SeverityLevel",
    "VulnerabilityType",
    # Marketing modelleri
    "AdCheckType",
    "AdDisapproval",
    "BudgetRecommendation",
    "CampaignMetrics",
    "KeywordMetrics",
    "MarketingAnalysisResult",
    "MarketingConfig",
    "PerformanceLevel",
    # Server modelleri
    "CpuMetrics",
    "DiskMetrics",
    "MetricStatus",
    "MetricThresholds",
    "RamMetrics",
    "ServerConfig",
    "ServerMetrics",
    "ServiceStatus",
    # Guvenlik modelleri
    "BannedIPEntry",
    "FailedLoginEntry",
    "OpenPort",
    "SecurityCheckType",
    "SecurityScanConfig",
    "SecurityScanResult",
    "SSLCertInfo",
    "SuspiciousProcess",
    "ThreatLevel",
    # Arastirma modelleri
    "CompanyInfo",
    "ReliabilityLevel",
    "ResearchConfig",
    "ResearchResult",
    "ResearchType",
    "ScrapedPage",
    "SupplierScore",
    "WebSearchResult",
    # Bildirim modelleri
    "NotificationChannel",
    "NotificationCreate",
    "NotificationEventType",
    "NotificationPriority",
    "NotificationRecord",
    "NotificationResponse",
    "NotificationStatus",
    # Gorev modelleri
    "TaskCreate",
    "TaskRecord",
    "TaskResponse",
    "TaskStatus",
    # Karar modelleri
    "DecisionCreate",
    "DecisionRecord",
    "DecisionResponse",
    # Agent log modelleri
    "AgentLogCreate",
    "AgentLogRecord",
    "AgentLogResponse",
    # Ses modelleri
    "CommandAnalysis",
    "CommandIntent",
    "SynthesisResult",
    "TranscriptionResult",
    "VoiceAnalysisResult",
    "VoiceConfig",
    "VoiceLanguage",
    "VoiceTaskType",
]
